name: "Git Board Flow"
description: "Issues, branches and pull requests linked."
author: "Landa Messenger"
inputs:
  action:
    description: "Action to handle"
    required: true
  emoji-labeled-title:
    description: "Title with emojis based on labels"
    default: "false"
  action-launcher-label:
    description: "Activation label for branch management"
    default: "git-board"
  hotfix-label:
    description: "Hotfix branch behaviour"
    default: "hotfix"
  bugfix-label:
    description: "Bugfix branch behaviour"
    default: "bugfix"
  feature-label:
    description: "Feature branch behaviour"
    default: "feature"
  question-label:
    description: "Label for detecting questions"
    default: "question"
  help-label:
    description: "Label for detecting help requests"
    default: "help"
  project-urls:
    description: "List of projects urls to link issues and pull requests"
    default: ""
  main-branch:
    description: "Main branch of the repository"
    default: "master"
  development-branch:
    description: "Development branch of the repository"
    default: "develop"
  feature-tree:
    description: "Tree for new features"
    default: "feature"
  bugfix-tree:
    description: "Tree for new bugfix"
    default: "bugfix"
  hotfix-tree:
    description: "Tree for new hotfix"
    default: "hotfix"
  images-clean-up:
    description: "Images for displaying on cleanup action comments"
    default: ""
  images-feature:
    description: "Images for displaying on feature action comments"
    default: ""
  images-bugfix:
    description: "Images for displaying on bugfix action comments"
    default: ""
  images-hotfix:
    description: "Images for displaying on hotfix action comments"
    default: ""
  images-pr-link:
    description: "Images for displaying on pull request link action comments"
    default: ""
  run-always:
    description: "Set if action-launcher-label is needed or not for launching git-board"
    default: "false"
  github-token:
    description: "GitHub token to interact with branches and projects in the current scope"
    required: true
  github-token-personal:
    description: "GitHub PAT to interact with commits, branches and projects"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: git-branch
  color: "gray-dark"
