name: "Git Board Flow"
description: "Issues, branches and pull requests linked."
author: "Landa Messenger"
inputs:
  action:
    description: "Action to handle"
    required: true
  branch-management-label:
    description: "Activation label for branch management"
    default: "branching"
  hotfix-label:
    description: "Hotfix branch behaviour"
    default: "hotfix"
  bugfix-label:
    description: "Bugfix branch behaviour"
    default: "bugfix"
  project-urls:
    description: "List of projects urls to link issues and pull requests"
    default: ""
  default-branch:
    description: "Default branch of the repository"
    default: "master"
  development-branch:
    description: "Development branch of the repository"
    default: "develop"
  github-token:
    description: "GitHub token to interact with branches and projects in the current scope"
    required: true
  github-token-personal:
    description: "GitHub PAT to interact with commits, branches and projects"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: git-branch
  color: "gray-dark"
