name: "Git Board Flow"
description: "Automates branch management, GitHub project linking, and issue/PR tracking with Git-Flow methodology."
author: "Landa Messenger"
inputs:
  action:
    description: "Specifies the action to perform (e.g., manage branches, link projects)."
    required: true
  emoji-labeled-title:
    description: "Enable titles with emojis based on issue labels."
    default: "false"
  action-launcher-label:
    description: "Label to trigger branch management actions."
    default: "git-board-flow"
  hotfix-label:
    description: "Label to manage hotfix branches."
    default: "hotfix"
  release-label:
    description: "Label to manage release branches."
    default: "release"
  bugfix-label:
    description: "Label to manage bugfix branches."
    default: "bugfix"
  feature-label:
    description: "Label to manage feature branches."
    default: "feature"
  question-label:
    description: "Label to detect issues marked as questions."
    default: "question"
  help-label:
    description: "Label to detect help request issues."
    default: "help"
  project-urls:
    description: "Comma-separated list of project URLs to link issues and pull requests."
    default: ""
  main-branch:
    description: "Name of the main branch (e.g., master)."
    default: "master"
  development-branch:
    description: "Name of the development branch (e.g., develop)."
    default: "develop"
  feature-tree:
    description: "Naming convention for feature branches."
    default: "feature"
  bugfix-tree:
    description: "Naming convention for bugfix branches."
    default: "bugfix"
  hotfix-tree:
    description: "Naming convention for hotfix branches."
    default: "hotfix"
  release-tree:
    description: "Naming convention for release branches."
    default: "release"
  images-clean-up:
    description: "Image URLs to display in cleanup action comments."
    default: ""
  images-feature:
    description: "Image URLs to display in feature action comments."
    default: ""
  images-bugfix:
    description: "Image URLs to display in bugfix action comments."
    default: ""
  images-hotfix:
    description: "Image URLs to display in hotfix action comments."
    default: ""
  images-release:
    description: "Image URLs to display in release action comments."
    default: ""
  images-pr-link:
    description: "Image URLs to display in PR linking action comments."
    default: ""
  run-always:
    description: "If true, ignores the action-launcher-label requirement for running Git Board."
    default: "false"
  commit-prefix-builder:
    description: "Enable commit prefix generation."
    default: "false"
  github-token:
    description: "GitHub token for branch and project operations within the repository scope."
    required: true
  github-token-personal:
    description: "GitHub PAT for extended operations on commits, branches, and projects."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "git-branch"
  color: "gray-dark"
