name: Prepare Files

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  prepare-files:
    name: Update compiled files
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: actions/checkout@v4

      - name: Switch to SSH
        run: git remote set-url origin git@github.com:landamessenger/git-board-flow.git

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Commit updated dist directory
        uses: EndBug/add-and-commit@v9
        with:
          add: './dist/'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          default_author: user_info
          message: 'gh-action: updated compiled files'
