name: Prepare Release

on:
  pull_request:
    types:
      - closed

jobs:
  prepare-release:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' }}
    name: Update version and compile files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Read and increment version
        id: increment_version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            const version = packageJson.version;

            const [major, minor, patch] = version.split('.').map(Number);
            const newVersion = `${major}.${minor}.${patch + 1}`;

            console.log(`Current version: ${version}`);
            console.log(`New version: ${newVersion}`);            

            packageJson.version = newVersion;
            fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));
            
            core.exportVariable('VERSION', newVersion)

      - name: Commit updated package.json and dist directory
        uses: EndBug/add-and-commit@v9
        with:
          add: './dist/ ./package.json'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          default_author: user_info
          message: 'gh-action: updated compiled files and bumped version to ${{ env.VERSION }}'
