name: Publish Release

on:
  workflow_run:
    workflows: ["Prepare Release"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read and increment version with TypeScript
        id: increment_version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            const version = packageJson.version;
            core.exportVariable('VERSION', version)

      - name: Create tag
        id: create_tag
        run: |
          # Check if the tag already exists in the remote repository
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists."
          else
            # Create and push the new tag
            git tag "v${{ env.VERSION }}"
            git push origin "v${{ env.VERSION }}"
          fi
